<?php
define('PATHIMAGENES','Webroot/media/');
$vistas=[
    'inicio'=>'View/vinicio.php',
    'carta'=>'View/vcarta.php',
    'reservas'=>'View/vreservas.php',
    'contacto'=>'View/vcontacto.php',
    'login'=>'View/vlogin.php',
    'panel'=>'View/vpanel.php',
    'productos'=>'View/vproductos.php',
    'insertarProducto'=>'View/vinsertarProducto.php',
    'eliminarProducto'=>'View/veliminarProducto.php',
    'editarProducto'=>'View/veditarProducto.php'
];
$controladores=[
    'inicio'=>'Controller/cinicio.php',
    'carta'=>'Controller/ccarta.php',
    'reservas'=>'Controller/creservas.php',
    'contacto'=>'Controller/ccontacto.php',
    'login'=>'Controller/clogin.php',
    'panel'=>'Controller/cpanel.php',
    'productos'=>'Controller/cproductos.php',
    'insertarProducto'=>'Controller/cinsertarProducto.php',
    'eliminarProducto'=>'Controller/celiminarProducto.php',
    'editarProducto'=>'Controller/ceditarProducto.php'

];
?>