<?php
define('PATHIMAGENES','Webroot/media/');
$vistas=[
    'inicio'=>'View/vinicio.php',
    'carta'=>'View/vcarta.php',
    'reservas'=>'View/vreservas.php',
    'contacto'=>'View/vcontacto.php',
    'login'=>'View/vlogin.php',
    'panel'=>'View/vpanel.php',
    'productos'=>'View/vproductos.php',
    'insertarProducto'=>'View/vinsertarProducto.php',
    'eliminarProducto'=>'View/veliminarProducto.php',
    'editarProducto'=>'View/veditarProducto.php',
    'modificarAdmin'=>'View/vmodificarAdmin.php',
    'panelReservas'=>'View/vpanelReservas.php',
    'borrarReserva'=>'View/vborrarReserva.php',
    'editarReserva'=>'View/veditarReserva.php',
    'terminarReserva'=>'View/vpanelReservas.php'

];
$controladores=[
    'inicio'=>'Controller/cinicio.php',
    'carta'=>'Controller/ccarta.php',
    'reservas'=>'Controller/creservas.php',
    'contacto'=>'Controller/ccontacto.php',
    'login'=>'Controller/clogin.php',
    'panel'=>'Controller/cpanel.php',
    'productos'=>'Controller/cproductos.php',
    'insertarProducto'=>'Controller/cinsertarProducto.php',
    'eliminarProducto'=>'Controller/celiminarProducto.php',
    'editarProducto'=>'Controller/ceditarProducto.php',
    'modificarAdmin'=>'Controller/cmodificarAdmin.php',
    'panelReservas'=>'Controller/cpanelReservas.php',
    'borrarReserva'=>'Controller/cborrarReserva.php',
    'editarReserva'=>'Controller/ceditarReserva.php',
    'terminarReserva'=>'Controller/cterminarReserva.php'
];
?>